# Generated by Django 5.2.7 on 2025-12-03 18:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('attempt_type', models.CharField(choices=[('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('MIXED', 'Mixed (All Types)')], max_length=20, verbose_name='Attempt Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('attempts_count', models.PositiveIntegerField(default=1, verbose_name='Attempts Count')),
                ('writing_attempts', models.PositiveIntegerField(default=0)),
                ('speaking_attempts', models.PositiveIntegerField(default=0)),
                ('reading_attempts', models.PositiveIntegerField(default=0)),
                ('listening_attempts', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (UZS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Attempt Package',
                'verbose_name_plural': 'Attempt Packages',
                'db_table': 'attempt_packages',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plan Name')),
                ('plan_type', models.CharField(choices=[('PLUS', 'Plus'), ('PRO', 'Pro'), ('ULTRA', 'Ultra')], max_length=20, unique=True, verbose_name='Plan Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (UZS)')),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20, verbose_name='Billing Period')),
                ('writing_attempts', models.PositiveIntegerField(default=0, help_text='Number of writing check attempts per month', verbose_name='Writing Attempts')),
                ('speaking_attempts', models.PositiveIntegerField(default=0, help_text='Number of speaking practice attempts per month', verbose_name='Speaking Attempts')),
                ('reading_attempts', models.PositiveIntegerField(default=0, help_text='Number of premium reading section attempts per month', verbose_name='Premium Reading Attempts')),
                ('listening_attempts', models.PositiveIntegerField(default=0, help_text='Number of premium listening section attempts per month', verbose_name='Premium Listening Attempts')),
                ('book_access', models.BooleanField(default=False, help_text='Access to premium books', verbose_name='Premium Books Access')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this plan', verbose_name='Features')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_popular', models.BooleanField(default=False, help_text="Show 'Most Popular' badge", verbose_name='Popular Badge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Order ID')),
                ('order_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('ATTEMPTS', 'Attempt Package')], max_length=20, verbose_name='Order Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount (UZS)')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('attempt_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.attemptpackage', verbose_name='Attempt Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionplan', verbose_name='Subscription Plan')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_attempts', models.PositiveIntegerField(default=0, verbose_name='Writing Attempts')),
                ('speaking_attempts', models.PositiveIntegerField(default=0, verbose_name='Speaking Attempts')),
                ('reading_attempts', models.PositiveIntegerField(default=0, verbose_name='Premium Reading Attempts')),
                ('listening_attempts', models.PositiveIntegerField(default=0, verbose_name='Premium Listening Attempts')),
                ('last_reset_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Reset Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Attempts',
                'verbose_name_plural': 'User Attempts',
                'db_table': 'user_attempts',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Payment')], default='PENDING', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Auto Renew')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionplan', verbose_name='Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='AttemptUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('WRITING', 'Writing Check'), ('SPEAKING', 'Speaking Practice'), ('READING', 'Premium Reading'), ('LISTENING', 'Premium Listening')], max_length=20, verbose_name='Usage Type')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Content Type')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Content ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Used At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Attempt Usage Log',
                'verbose_name_plural': 'Attempt Usage Logs',
                'db_table': 'attempt_usage_logs',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', 'usage_type'], name='attempt_usa_user_id_cea8ef_idx'), models.Index(fields=['used_at'], name='attempt_usa_used_at_4a6ed2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=50, unique=True, verbose_name='Payme Transaction ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Completed'), (-1, 'Cancelled after create'), (-2, 'Cancelled after complete')], default=1, verbose_name='State')),
                ('amount', models.BigIntegerField(verbose_name='Amount (Tiyins)')),
                ('payme_time', models.BigIntegerField(help_text='Timestamp from Payme in milliseconds', verbose_name='Payme Create Time')),
                ('create_time', models.BigIntegerField(help_text='Our create timestamp in milliseconds', verbose_name='Create Time')),
                ('perform_time', models.BigIntegerField(default=0, help_text='Transaction perform timestamp in milliseconds', verbose_name='Perform Time')),
                ('cancel_time', models.BigIntegerField(default=0, help_text='Transaction cancel timestamp in milliseconds', verbose_name='Cancel Time')),
                ('reason', models.SmallIntegerField(blank=True, choices=[(1, 'Receiver not found'), (2, 'Debit operation error'), (3, 'Transaction execution error'), (4, 'Timeout cancellation'), (5, 'Refund'), (10, 'Unknown error')], null=True, verbose_name='Cancel Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payme Transaction',
                'verbose_name_plural': 'Payme Transactions',
                'db_table': 'payme_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payme_id'], name='payme_trans_payme_i_c9f7ce_idx'), models.Index(fields=['state'], name='payme_trans_state_1a024d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['order_id'], name='payment_ord_order_i_d7c1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='payment_ord_user_id_5f4b4e_idx'),
        ),
    ]
