# Generated by Django 5.2.7 on 2025-12-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='listening_attempts',
            field=models.IntegerField(default=0, help_text='Number of premium listening section attempts per month (-1 for unlimited)', verbose_name='Premium Listening Attempts'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='reading_attempts',
            field=models.IntegerField(default=0, help_text='Number of premium reading section attempts per month (-1 for unlimited)', verbose_name='Premium Reading Attempts'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='speaking_attempts',
            field=models.IntegerField(default=0, help_text='Number of speaking practice attempts per month (-1 for unlimited)', verbose_name='Speaking Attempts'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='writing_attempts',
            field=models.IntegerField(default=0, help_text='Number of writing check attempts per month (-1 for unlimited)', verbose_name='Writing Attempts'),
        ),
    ]
