# Generated by Django 5.2.7 on 2025-12-04 18:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscriptionplan_listening_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount (UZS)'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount before discount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Original Amount (UZS)'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promotional code (case-insensitive)', max_length=50, unique=True, verbose_name='Promo Code')),
                ('description', models.TextField(blank=True, help_text='Internal description for this promo code', null=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount in UZS', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Value')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to use this code (UZS)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Purchase Amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on discount amount for percentage discounts (UZS)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Discount Amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total uses (leave blank for unlimited)', null=True, verbose_name='Total Usage Limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user', verbose_name='Per-User Limit')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Total times this code has been used', verbose_name='Times Used')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Start date (leave blank for immediate)', null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, help_text='End date (leave blank for no expiry)', null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Leave empty to apply to all plans', related_name='promo_codes', to='payments.subscriptionplan', verbose_name='Applicable Plans')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.promocode', verbose_name='Promo Code Applied'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Original Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Discount Amount')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Final Amount')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Used At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usage', to='payments.paymentorder', verbose_name='Order')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.promocode', verbose_name='Promo Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'db_table': 'promo_code_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promo_codes_code_5b1d05_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active'], name='promo_codes_is_acti_856e08_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['promo_code', 'user'], name='promo_code__promo_c_69f07c_idx'),
        ),
    ]
