# Generated by Django 5.2.7 on 2025-12-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', '3 Months'), ('BIANNUAL', '6 Months'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20, verbose_name='Billing Period'),
        ),
    ]
