# Generated by Django 5.2.7 on 2025-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_quarterly_biannual_billing_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='cd_exam_attempts',
            field=models.IntegerField(default=0, help_text='Number of free CD exam attempts included in the plan', verbose_name='CD Exam Attempts'),
        ),
        migrations.AddField(
            model_name='userattempts',
            name='cd_exam_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='CD Exam Attempts'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plan Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('PLUS', 'Plus'), ('PRO', 'Pro'), ('ULTRA', 'Ultra')], max_length=20, verbose_name='Plan Type'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('plan_type', 'billing_period')},
        ),
    ]
