# Generated by Django 5.2.7 on 2025-11-21 19:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ielts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for secure access', unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Exam Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(blank=True, help_text='When students can start taking this exam', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the exam closes', null=True, verbose_name='End Date')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit for completing the exam', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (minutes)')),
                ('is_public', models.BooleanField(default=False, help_text='If true, all students can access. If false, only assigned students.', verbose_name='Public')),
                ('access_code', models.CharField(blank=True, help_text='Optional access code for students', max_length=50, null=True, verbose_name='Access Code')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('auto_grade_reading', models.BooleanField(default=True, verbose_name='Auto-grade Reading')),
                ('auto_grade_listening', models.BooleanField(default=True, verbose_name='Auto-grade Listening')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Students')),
                ('mock_exam', models.ForeignKey(blank=True, help_text='Optional: Use an existing IELTS mock exam as template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_exams', to='ielts.mockexam', verbose_name='IELTS Mock Exam Template')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Exam',
                'verbose_name_plural': 'Teacher Exams',
                'db_table': 'teacher_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('GRADED', 'Graded')], default='NOT_STARTED', max_length=20, verbose_name='Status')),
                ('current_section', models.CharField(default='NOT_STARTED', help_text='Current section: NOT_STARTED, listening, reading, writing, speaking, or COMPLETED', max_length=20, verbose_name='Current Section')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('listening_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Listening Score')),
                ('reading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Reading Score')),
                ('writing_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Writing Score')),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Speaking Score')),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Overall Band Score')),
                ('detailed_scores', models.JSONField(blank=True, help_text='Detailed breakdown of scores by question, section, criteria, etc.', null=True)),
                ('strengths', models.JSONField(blank=True, default=list, help_text="List of student's strong areas", null=True)),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text="List of student's weak areas", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teacher.teacherexam', verbose_name='Exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Teacher Exam Attempt',
                'verbose_name_plural': 'Teacher Exam Attempts',
                'db_table': 'teacher_exam_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('GENERAL', 'General Feedback'), ('LISTENING', 'Listening Feedback'), ('READING', 'Reading Feedback'), ('WRITING', 'Writing Feedback'), ('SPEAKING', 'Speaking Feedback')], default='GENERAL', max_length=20, verbose_name='Feedback Type')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('task_achievement', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Task Achievement/Response')),
                ('coherence_cohesion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Coherence and Cohesion')),
                ('lexical_resource', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Lexical Resource')),
                ('grammatical_range', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Grammatical Range and Accuracy')),
                ('pronunciation', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Pronunciation')),
                ('fluency_coherence', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Fluency and Coherence')),
                ('is_visible_to_student', models.BooleanField(default=True, verbose_name='Visible to Student')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedbacks', to='teacher.teacherexamattempt', verbose_name='Exam Attempt')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Feedback',
                'verbose_name_plural': 'Teacher Feedbacks',
                'db_table': 'teacher_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='teacher.teacherexamattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user_answers', to='ielts.question')),
            ],
            options={
                'verbose_name': 'Teacher User Answer',
                'verbose_name_plural': 'Teacher User Answers',
                'db_table': 'teacher_user_answers',
                'ordering': ['question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherexam',
            index=models.Index(fields=['teacher', 'status'], name='teacher_exa_teacher_0d9959_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherexam',
            index=models.Index(fields=['status', 'start_date'], name='teacher_exa_status_2f02f9_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherexamattempt',
            index=models.Index(fields=['exam', 'status'], name='teacher_exa_exam_id_33a357_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherexamattempt',
            index=models.Index(fields=['student', 'status'], name='teacher_exa_student_12817b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherexamattempt',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='teacherfeedback',
            index=models.Index(fields=['attempt', 'feedback_type'], name='teacher_fee_attempt_9e4405_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherfeedback',
            index=models.Index(fields=['teacher'], name='teacher_fee_teacher_f437c3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheruseranswer',
            index=models.Index(fields=['exam_attempt', 'is_correct'], name='teacher_use_exam_at_70dc2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacheruseranswer',
            unique_together={('exam_attempt', 'question')},
        ),
    ]
