# Generated by Django 5.2.7 on 2025-11-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherwritingattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teacherwritingattempt',
            new_name='teacher_wri_exam_at_3805ad_idx',
            old_name='teacher_wri_exam_at_idx',
        ),
    ]
