# Generated by Django 5.2.7 on 2025-11-06 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ielts', '0004_speakingtopic_is_authentic_writingtask_is_authentic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Cambridge IELTS 15', max_length=255, verbose_name='Book Title')),
                ('description', models.TextField(blank=True, help_text='Book description', null=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, help_text='Book cover image', null=True, upload_to='books/covers/', verbose_name='Cover Image')),
                ('level', models.CharField(choices=[('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='B2', help_text='Common European Framework of Reference level', max_length=2, verbose_name='CEFR Level')),
                ('total_sections', models.PositiveIntegerField(default=0, help_text='Total number of practice sections in this book', verbose_name='Total Sections')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Publication Year')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this book is available', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='books_level_4b73cd_idx'), models.Index(fields=['is_active'], name='books_is_acti_a3aae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Test 1 - Reading Passage 1', max_length=255, verbose_name='Section Title')),
                ('section_type', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening')], help_text='Reading or Listening', max_length=20, verbose_name='Section Type')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of this section within the book', verbose_name='Order')),
                ('description', models.TextField(blank=True, help_text='Section overview', null=True, verbose_name='Description')),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total number of questions in this section', verbose_name='Total Questions')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Expected time to complete this section', null=True, verbose_name='Duration (minutes)')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this section is locked (requires previous sections completed)', verbose_name='Locked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='books.book', verbose_name='Book')),
                ('listening_part', models.ForeignKey(blank=True, help_text='Link to an existing listening part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_sections', to='ielts.listeningpart', verbose_name='Listening Part')),
                ('reading_passage', models.ForeignKey(blank=True, help_text='Link to an existing reading passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_sections', to='ielts.readingpassage', verbose_name='Reading Passage')),
            ],
            options={
                'verbose_name': 'Book Section',
                'verbose_name_plural': 'Book Sections',
                'db_table': 'book_sections',
                'ordering': ['book', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserBookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_sections', models.PositiveIntegerField(default=0, verbose_name='Completed Sections')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all section scores', max_digits=5, verbose_name='Total Score')),
                ('average_score', models.DecimalField(blank=True, decimal_places=1, help_text='Average IELTS band score across all completed sections', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Average Band Score')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Completion Percentage')),
                ('is_started', models.BooleanField(default=False, help_text='Has the user started this book', verbose_name='Started')),
                ('is_completed', models.BooleanField(default=False, help_text='Has the user completed all sections', verbose_name='Completed')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time user accessed this book', verbose_name='Last Accessed')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='books.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Book Progress',
                'verbose_name_plural': 'User Book Progress',
                'db_table': 'user_book_progress',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='UserSectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, help_text='IELTS band score (0-9)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Band Score')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Correct Answers')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Accuracy %')),
                ('answers', models.JSONField(blank=True, help_text="Stores user's answers in JSON format", null=True, verbose_name='User Answers')),
                ('time_spent', models.PositiveIntegerField(blank=True, help_text='Time taken to complete the section in seconds', null=True, verbose_name='Time Spent (seconds)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('attempt_date', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='books.booksection', verbose_name='Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Section Result',
                'verbose_name_plural': 'User Section Results',
                'db_table': 'user_section_results',
                'ordering': ['-attempt_date'],
            },
        ),
        migrations.AddIndex(
            model_name='booksection',
            index=models.Index(fields=['book', 'section_type'], name='book_sectio_book_id_6c00dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booksection',
            index=models.Index(fields=['book', 'order'], name='book_sectio_book_id_e7347d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booksection',
            unique_together={('book', 'order')},
        ),
        migrations.AddIndex(
            model_name='userbookprogress',
            index=models.Index(fields=['user', 'is_completed'], name='user_book_p_user_id_bdd74b_idx'),
        ),
        migrations.AddIndex(
            model_name='userbookprogress',
            index=models.Index(fields=['user', 'last_accessed'], name='user_book_p_user_id_444b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbookprogress',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='usersectionresult',
            index=models.Index(fields=['user', 'section'], name='user_sectio_user_id_1831ff_idx'),
        ),
        migrations.AddIndex(
            model_name='usersectionresult',
            index=models.Index(fields=['user', 'is_completed'], name='user_sectio_user_id_8771c8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersectionresult',
            index=models.Index(fields=['section', 'score'], name='user_sectio_section_2de78b_idx'),
        ),
    ]
