# Generated by Django 5.2.7 on 2025-11-14 09:46

from django.db import migrations
import uuid


def populate_uuids(apps, schema_editor):
    """Populate UUID fields for existing records"""
    UserSectionResult = apps.get_model("books", "UserSectionResult")

    # Update UserSectionResult records
    for obj in UserSectionResult.objects.all():
        if not obj.uuid:
            obj.uuid = uuid.uuid4()
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
    ]
