# Generated by Django 5.2.7 on 2025-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Requires subscription or attempts to access', verbose_name='Premium Content'),
        ),
    ]
