# Generated by Django 5.2.7 on 2025-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksection',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Test 1 - Reading Passage 1 (auto-generated if empty)', max_length=255, verbose_name='Section Title'),
        ),
    ]
