# Generated by Django 5.2.7 on 2025-11-14 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_populate_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersectionresult',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for secure access', unique=True, verbose_name='UUID'),
        ),
    ]
