# Generated by Django 5.2.7 on 2025-12-08 20:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this configuration (e.g., 'Production Gemini', 'Backup OpenAI')", max_length=100)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], default='gemini', help_text='AI provider to use', max_length=20)),
                ('api_key', models.CharField(help_text='API key for the provider (encrypted at rest)', max_length=500)),
                ('model_name', models.CharField(help_text="Model name to use (e.g., 'gemini-2.5-pro', 'gpt-4', 'claude-3-opus')", max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary configuration to use for all AI operations')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is available for use')),
                ('temperature', models.FloatField(default=0.0, help_text='Temperature for AI generation (0.0-2.0, lower = more deterministic)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=8192, help_text='Maximum tokens for AI response', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)])),
                ('total_requests', models.IntegerField(default=0, help_text='Total API requests made')),
                ('total_tokens_used', models.IntegerField(default=0, help_text='Total tokens consumed')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this config was used', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if any', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'db_table': 'ai_configuration',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Which feature used the AI', max_length=100)),
                ('request_type', models.CharField(help_text='Type of request (writing_check, speaking_eval, content_gen)', max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(default=0, help_text='Response time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='manager_panel.aiconfiguration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
