# Generated by Django 5.2.7 on 2025-11-21 19:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('verification_code', models.CharField(max_length=6, verbose_name='Verification Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name': 'Telegram Verification',
                'verbose_name_plural': 'Telegram Verifications',
                'db_table': 'telegram_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=20, verbose_name='User Role')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Image')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification Code')),
                ('code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Code Expires At')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('telegram_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Phone')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('registration_method', models.CharField(choices=[('EMAIL', 'Email/Password'), ('TELEGRAM', 'Telegram'), ('GOOGLE', 'Google')], default='EMAIL', max_length=20, verbose_name='Registration Method')),
                ('balance', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Balance (UZS)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
