# Generated by Django 5.2.7 on 2025-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('verification_code', models.CharField(max_length=6, verbose_name='Verification Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name': 'Telegram Verification',
                'verbose_name_plural': 'Telegram Verifications',
                'db_table': 'telegram_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_verified',
            field=models.BooleanField(default=False, verbose_name='Telegram Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification Code'),
        ),
    ]
