# Generated by Django 5.2.7 on 2025-12-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Exam Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('ACADEMIC', 'Academic'), ('GENERAL', 'General Training'), ('UKVI', 'UKVI (UK Visas and Immigration)')], max_length=20, null=True, verbose_name='Exam Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='heard_from',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google Search'), ('SOCIAL_MEDIA', 'Social Media (Instagram, TikTok, etc.)'), ('FRIEND', 'Friend or Family'), ('YOUTUBE', 'YouTube'), ('TELEGRAM', 'Telegram'), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='How Did You Hear About Us'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_goal',
            field=models.CharField(blank=True, choices=[('STUDY_ABROAD', 'Study Abroad'), ('IMMIGRATION', 'Immigration'), ('WORK', 'Work or Career'), ('PERSONAL', 'Personal Development'), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='Main Goal'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_score',
            field=models.CharField(blank=True, choices=[('5.0', 'Band 5.0'), ('5.5', 'Band 5.5'), ('6.0', 'Band 6.0'), ('6.5', 'Band 6.5'), ('7.0', 'Band 7.0'), ('7.5', 'Band 7.5'), ('8.0', 'Band 8.0'), ('8.5', 'Band 8.5+')], max_length=10, null=True, verbose_name='Target Score'),
        ),
    ]
