# Generated by Django 5.2.7 on 2025-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code Expires At'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Verification Code'),
        ),
    ]
