# Generated by Django 5.2.7 on 2025-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('STUDENT', 'Student')], default='STUDENT', max_length=20, verbose_name='User Role'),
        ),
    ]
