# Generated by Django 5.2.7 on 2025-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Balance (UZS)'),
        ),
    ]
