# Generated by Django 5.2.7 on 2025-11-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('EMAIL', 'Email/Password'), ('TELEGRAM', 'Telegram'), ('GOOGLE', 'Google')], default='EMAIL', max_length=20, verbose_name='Registration Method'),
        ),
    ]
