# Generated by Django 5.2.7 on 2025-12-11 15:57

import classroom.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ielts', '0007_add_chart_type_to_writing_task'),
        ('teacher', '0004_teacherexam_results_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(help_text="e.g., 'Week 1 Homework', 'Reading Practice Set 3'", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Instructions or description for students', null=True, verbose_name='Description')),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice'), ('EXAM', 'Exam'), ('REMEDIAL', 'Remedial Practice')], default='HOMEWORK', max_length=20, verbose_name='Type')),
                ('teacher_instructions', models.TextField(blank=True, help_text="Special instructions to pass to the AI grader (e.g., 'Focus on passive voice', 'Check for academic vocabulary')", null=True, verbose_name='Teacher Instructions for AI')),
                ('available_from', models.DateTimeField(blank=True, help_text='When students can start working on this assignment', null=True, verbose_name='Available From')),
                ('due_date', models.DateTimeField(blank=True, help_text='When the assignment is due', null=True, verbose_name='Due Date')),
                ('allow_late_submission', models.BooleanField(default=True, verbose_name='Allow Late Submission')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Optional time limit for completing the bundle', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Time Limit (minutes)')),
                ('target_min_band', models.DecimalField(blank=True, decimal_places=1, help_text='Only assign to students with band >= this value', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Target Minimum Band')),
                ('target_max_band', models.DecimalField(blank=True, decimal_places=1, help_text='Only assign to students with band <= this value', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Target Maximum Band')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('require_teacher_approval', models.BooleanField(default=True, help_text="If true, AI grades go to 'pending_review' status; if false, auto-released to students", verbose_name='Require Teacher Approval')),
                ('auto_release_results', models.BooleanField(default=False, help_text='Automatically release results to students after AI grading', verbose_name='Auto-Release Results')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bundles', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Assignment Bundle',
                'verbose_name_plural': 'Assignment Bundles',
                'db_table': 'assignment_bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('item_type', models.CharField(choices=[('MOCK_EXAM', 'Full Mock Exam'), ('TEACHER_EXAM', 'Teacher Exam'), ('WRITING_TASK', 'Writing Task'), ('SPEAKING_TOPIC', 'Speaking Topic'), ('READING_PASSAGE', 'Reading Passage'), ('LISTENING_PART', 'Listening Part')], max_length=20, verbose_name='Item Type')),
                ('item_instructions', models.TextField(blank=True, help_text='Additional instructions specific to this item', null=True, verbose_name='Item-Specific Instructions')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the bundle', verbose_name='Order')),
                ('points', models.PositiveIntegerField(default=100, help_text='Points this item is worth', verbose_name='Points')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this item is required for completion', verbose_name='Required')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='classroom.assignmentbundle', verbose_name='Bundle')),
                ('listening_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_items', to='ielts.listeningpart', verbose_name='Listening Part')),
                ('mock_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_items', to='ielts.mockexam', verbose_name='Mock Exam')),
                ('reading_passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_items', to='ielts.readingpassage', verbose_name='Reading Passage')),
                ('speaking_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_items', to='ielts.speakingtopic', verbose_name='Speaking Topic')),
                ('teacher_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_items', to='teacher.teacherexam', verbose_name='Teacher Exam')),
                ('writing_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_items', to='ielts.writingtask', verbose_name='Writing Task')),
            ],
            options={
                'verbose_name': 'Bundle Item',
                'verbose_name_plural': 'Bundle Items',
                'db_table': 'bundle_items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for secure access', unique=True, verbose_name='UUID')),
                ('name', models.CharField(help_text="e.g., 'IELTS Band 7 Group A', 'Evening Class 2024'", max_length=255, verbose_name='Classroom Name')),
                ('description', models.TextField(blank=True, help_text='Additional details about the classroom', null=True, verbose_name='Description')),
                ('target_band', models.DecimalField(blank=True, decimal_places=1, help_text='The target IELTS band score for this class', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Target Band Score')),
                ('invite_code', models.CharField(db_index=True, default=classroom.models.generate_invite_code, help_text='Code for students to join this classroom', max_length=20, unique=True, verbose_name='Invite Code')),
                ('invite_enabled', models.BooleanField(default=True, help_text='Allow new students to join via invite link', verbose_name='Invite Enabled')),
                ('max_students', models.PositiveIntegerField(default=50, help_text='Maximum number of students allowed in this classroom', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Maximum Students')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'classrooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_bundles', to='classroom.classroom', verbose_name='Classroom'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LEFT', 'Left'), ('REMOVED', 'Removed by Teacher')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('current_band', models.DecimalField(blank=True, decimal_places=1, help_text='Current estimated band score based on performance', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Current Estimated Band')),
                ('listening_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Listening Band')),
                ('reading_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Reading Band')),
                ('writing_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Writing Band')),
                ('speaking_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Speaking Band')),
                ('notes', models.TextField(blank=True, help_text='Private notes about this student', null=True, verbose_name='Teacher Notes')),
                ('last_active', models.DateTimeField(blank=True, help_text='When the student was last active in this classroom', null=True, verbose_name='Last Active')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.classroom', verbose_name='Classroom')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'classroom_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AI_PROCESSED', 'AI Processed'), ('PENDING_REVIEW', 'Pending Teacher Review'), ('TEACHER_REVIEWED', 'Teacher Reviewed'), ('RETURNED', 'Returned to Student'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='AI Processed At')),
                ('teacher_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Teacher Reviewed At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall percentage or band score', max_digits=5, null=True, verbose_name='Overall Score')),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Band Score')),
                ('ai_feedback', models.JSONField(blank=True, help_text='Feedback generated by AI grading system', null=True, verbose_name='AI Feedback')),
                ('ai_tentative_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='AI Tentative Score')),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name='Teacher Feedback')),
                ('score_overridden', models.BooleanField(default=False, help_text="Whether the teacher overrode the AI's tentative score", verbose_name='Score Overridden')),
                ('item_progress', models.JSONField(default=dict, help_text='Progress tracking for each item in the bundle', verbose_name='Item Progress')),
                ('is_late', models.BooleanField(default=False, verbose_name='Late Submission')),
                ('results_visible', models.BooleanField(default=False, help_text='Whether the student can see their results', verbose_name='Results Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='classroom.assignmentbundle', verbose_name='Assignment Bundle')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Student Assignment',
                'verbose_name_plural': 'Student Assignments',
                'db_table': 'student_assignments',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentItemSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AI_GRADED', 'AI Graded'), ('TEACHER_REVIEWED', 'Teacher Reviewed')], default='NOT_STARTED', max_length=20, verbose_name='Status')),
                ('writing_answer', models.TextField(blank=True, null=True, verbose_name='Writing Answer')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Word Count')),
                ('speaking_audio', models.FileField(blank=True, null=True, upload_to='classroom/speaking_submissions/%Y/%m/', verbose_name='Speaking Audio')),
                ('speaking_transcript', models.TextField(blank=True, null=True, verbose_name='Speaking Transcript')),
                ('answers_json', models.JSONField(blank=True, help_text='JSON containing question IDs and user answers', null=True, verbose_name='Answers')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maximum Score')),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Band Score')),
                ('ai_feedback', models.JSONField(blank=True, null=True, verbose_name='AI Feedback')),
                ('ai_inline_corrections', models.TextField(blank=True, help_text='Text with inline error tags from AI', null=True, verbose_name='AI Inline Corrections')),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name='Teacher Feedback')),
                ('teacher_score_override', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Teacher Score Override')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Time Spent (seconds)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.bundleitem', verbose_name='Bundle Item')),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_submissions', to='classroom.studentassignment', verbose_name='Student Assignment')),
            ],
            options={
                'verbose_name': 'Student Item Submission',
                'verbose_name_plural': 'Student Item Submissions',
                'db_table': 'student_item_submissions',
                'ordering': ['bundle_item__order'],
            },
        ),
        migrations.AddIndex(
            model_name='bundleitem',
            index=models.Index(fields=['bundle', 'item_type'], name='bundle_item_bundle__f84065_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['teacher', 'status'], name='classrooms_teacher_6392fa_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['invite_code'], name='classrooms_invite__eaf9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentbundle',
            index=models.Index(fields=['classroom', 'status'], name='assignment__classro_3addf7_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentbundle',
            index=models.Index(fields=['due_date'], name='assignment__due_dat_402456_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['classroom', 'status'], name='classroom_e_classro_69983e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='classroom_e_student_1e6e37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('classroom', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['bundle', 'status'], name='student_ass_bundle__00e370_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['student', 'status'], name='student_ass_student_fbfd68_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['status'], name='student_ass_status_f76598_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentassignment',
            unique_together={('bundle', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentitemsubmission',
            index=models.Index(fields=['student_assignment', 'status'], name='student_ite_student_969e6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentitemsubmission',
            unique_together={('student_assignment', 'bundle_item')},
        ),
    ]
