# Generated by Django 5.2.7 on 2025-11-30 10:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ielts', '0003_listeningpart_is_practice_readingpassage_is_practice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(help_text='Practice section title', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('section_type', models.CharField(choices=[('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], db_index=True, max_length=20, verbose_name='Section Type')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy (Band 4-5)'), ('MEDIUM', 'Medium (Band 5.5-6.5)'), ('HARD', 'Hard (Band 7-8)'), ('EXPERT', 'Expert (Band 8.5-9)')], default='MEDIUM', max_length=20, verbose_name='Difficulty')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Leave empty to use IELTS standard duration', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (minutes)')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_free', models.BooleanField(default=False, help_text='Available without premium subscription', verbose_name='Free Access')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_section_practices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('listening_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_practices', to='ielts.listeningpart', verbose_name='Listening Part')),
                ('reading_passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_practices', to='ielts.readingpassage', verbose_name='Reading Passage')),
                ('speaking_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_practices', to='ielts.speakingtopic', verbose_name='Speaking Topic')),
                ('writing_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_practices', to='ielts.writingtask', verbose_name='Writing Task')),
            ],
            options={
                'verbose_name': 'Section Practice',
                'verbose_name_plural': 'Section Practices',
                'db_table': 'section_practices',
                'ordering': ['section_type', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Time Spent (seconds)')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Band Score')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Correct Answers')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Submitted Answers')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='AI Feedback')),
                ('ai_evaluation', models.JSONField(blank=True, null=True, verbose_name='AI Evaluation Details')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.sectionpractice', verbose_name='Section Practice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_practice_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Section Practice Attempt',
                'verbose_name_plural': 'Section Practice Attempts',
                'db_table': 'section_practice_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sectionpractice',
            index=models.Index(fields=['section_type', 'is_active'], name='section_pra_section_b9a50e_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionpractice',
            index=models.Index(fields=['difficulty'], name='section_pra_difficu_ee0850_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionpracticeattempt',
            index=models.Index(fields=['student', 'status'], name='section_pra_student_74c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionpracticeattempt',
            index=models.Index(fields=['practice', 'student'], name='section_pra_practic_ec9398_idx'),
        ),
    ]
