# Generated by Django 5.2.7 on 2025-12-02 16:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPracticeRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('question_key', models.CharField(help_text='Identifier for the question (e.g., part1_q1, part2, part3_q1)', max_length=50, verbose_name='Question Key')),
                ('audio_file', models.FileField(upload_to='speaking_practice_recordings/%Y/%m/%d/', verbose_name='Audio Recording')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='Transcription')),
                ('ai_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='AI Score')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='AI Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='practice.sectionpracticeattempt', verbose_name='Practice Attempt')),
            ],
            options={
                'verbose_name': 'Speaking Practice Recording',
                'verbose_name_plural': 'Speaking Practice Recordings',
                'db_table': 'speaking_practice_recordings',
                'ordering': ['attempt', 'question_key'],
                'indexes': [models.Index(fields=['attempt', 'question_key'], name='speaking_pr_attempt_1a34cb_idx')],
                'unique_together': {('attempt', 'question_key')},
            },
        ),
    ]
