# Generated by Django 5.2.7 on 2025-01-26 09:45

import django.core.validators
import django.db.models.deletion
import ielts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeningPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Part 1"),
                            (2, "Part 2"),
                            (3, "Part 3"),
                            (4, "Part 4"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload the audio file for this listening part",
                        null=True,
                        upload_to="ielts/listening_audio/",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the audio in seconds",
                        null=True,
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, help_text="Full transcript of the audio", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["part_number"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="The order in which the question appears for this passage.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "correct_answer_text",
                    models.CharField(
                        blank=True,
                        help_text="The correct answer for T/F/NG or Short Answer questions.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "answer_two_text",
                    models.CharField(
                        blank=True,
                        help_text="Second correct answer for MCMA questions",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "answer_three_text",
                    models.CharField(
                        blank=True,
                        help_text="Third correct answer for MCMA questions",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReadingPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passage_number",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Passage 1"), (2, "Passage 2"), (3, "Passage 3")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the reading passage.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="A brief summary or introduction to the passage.",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The full text of the reading passage."),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate word count of the passage",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["passage_number"],
            },
        ),
        migrations.CreateModel(
            name="SpeakingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "speaking_type",
                    models.CharField(
                        choices=[
                            ("PART_1", "Part 1: Introduction & Interview"),
                            ("PART_2", "Part 2: Individual Long Turn"),
                            ("PART_3", "Part 3: Two-way Discussion"),
                        ],
                        default="PART_1",
                        help_text="The part of speaking test",
                        max_length=10,
                        verbose_name="Speaking Part",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        blank=True,
                        help_text="Question or prompt for the topic.",
                        null=True,
                    ),
                ),
                (
                    "cue_card",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of points to cover (for Part 2)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["speaking_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="WritingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("TASK_1", "Task 1"), ("TASK_2", "Task 2")],
                        max_length=10,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="The full text of the task prompt."),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="writing_tasks/pictures/",
                        verbose_name="Task Picture",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="For Task 1, stores graph/chart data.",
                        null=True,
                    ),
                ),
                (
                    "min_words",
                    models.PositiveIntegerField(
                        default=150,
                        help_text="Minimum word count (150 for Task 1, 250 for Task 2)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["task_type"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the scheduled exam",
                        max_length=255,
                        verbose_name="Exam Name",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price for attending this exam (so'm). Leave empty for free exams.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the exam becomes available",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "expire_date",
                    models.DateTimeField(
                        help_text="When the exam is no longer available",
                        verbose_name="Expire Date",
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        help_text="PIN code for students to attend this exam",
                        max_length=20,
                        unique=True,
                        verbose_name="PIN Code",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of students allowed. Leave empty for unlimited.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Max Students",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about this exam",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["MANAGER", "SUPERADMIN"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "enrolled_students",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "STUDENT"},
                        related_name="enrolled_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enrolled Students",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Exam",
                "verbose_name_plural": "Scheduled Exams",
                "db_table": "scheduled_exams",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("EVALUATED", "Evaluated"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "current_section",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("EVALUATED", "Evaluated"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Current Section",
                    ),
                ),
                (
                    "listening_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Listening Score",
                    ),
                ),
                (
                    "reading_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Reading Score",
                    ),
                ),
                (
                    "writing_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Writing Score",
                    ),
                ),
                (
                    "speaking_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Speaking Score",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Overall Score",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="ielts.exam",
                        verbose_name="Exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Attempt",
                "verbose_name_plural": "Exam Attempts",
                "db_table": "exam_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listening_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Listening Score",
                    ),
                ),
                (
                    "reading_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Reading Score",
                    ),
                ),
                (
                    "writing_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Writing Score",
                    ),
                ),
                (
                    "speaking_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Speaking Score",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Overall Score",
                    ),
                ),
                (
                    "listening_correct",
                    models.IntegerField(
                        default=0, verbose_name="Listening Correct Answers"
                    ),
                ),
                (
                    "reading_correct",
                    models.IntegerField(
                        default=0, verbose_name="Reading Correct Answers"
                    ),
                ),
                (
                    "writing_task1_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Writing Task 1 Score",
                    ),
                ),
                (
                    "writing_task2_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Writing Task 2 Score",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Evaluated At"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="Feedback"),
                ),
                (
                    "detailed_feedback",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed feedback for each section/question",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="ielts.examattempt",
                        verbose_name="Exam Attempt",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Evaluated By",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ielts.exam",
                        verbose_name="Exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Result",
                "verbose_name_plural": "Exam Results",
                "db_table": "exam_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Exam Title")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("LISTENING", "Listening"),
                            ("READING", "Reading"),
                            ("WRITING", "Writing"),
                            ("SPEAKING", "Speaking"),
                            ("LISTENING_READING", "Listening + Reading"),
                            (
                                "LISTENING_READING_WRITING",
                                "Listening + Reading + Writing",
                            ),
                            ("FULL_TEST", "Full Test"),
                        ],
                        max_length=30,
                        verbose_name="Exam Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave empty to use IELTS standard duration",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner (Band 3-4)"),
                            ("INTERMEDIATE", "Intermediate (Band 5-6)"),
                            ("ADVANCED", "Advanced (Band 7-8)"),
                            ("EXPERT", "Expert (Band 8.5-9)"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                        verbose_name="Difficulty Level",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "listening_parts",
                    models.ManyToManyField(
                        related_name="mock_tests", to="ielts.listeningpart"
                    ),
                ),
                (
                    "reading_passages",
                    models.ManyToManyField(
                        blank=True, related_name="mock_tests", to="ielts.readingpassage"
                    ),
                ),
                (
                    "speaking_topics",
                    models.ManyToManyField(
                        related_name="mock_tests", to="ielts.speakingtopic"
                    ),
                ),
                (
                    "writing_tasks",
                    models.ManyToManyField(
                        related_name="mock_tests", to="ielts.writingtask"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Exam",
                "verbose_name_plural": "Mock Exams",
                "db_table": "exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="mock_test",
            field=models.ForeignKey(
                help_text="The mock test template to use for this exam",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_exams",
                to="ielts.mockexam",
                verbose_name="Mock Test",
            ),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=255)),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this if it is the correct answer for the multiple-choice question.",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="ielts.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeakingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_files",
                    models.JSONField(
                        blank=True,
                        help_text="e.g., {'part_1': 'path/to/audio1.mp3', ...}",
                        null=True,
                    ),
                ),
                (
                    "transcripts",
                    models.JSONField(
                        blank=True,
                        help_text="Transcripts for each speaking part",
                        null=True,
                    ),
                ),
                (
                    "feedback",
                    models.JSONField(
                        blank=True,
                        default=ielts.models.SpeakingAttempt._default_feedback_speaking,
                        help_text="Stores detailed AI feedback and scores for each criterion.",
                        null=True,
                    ),
                ),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "band_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "fluency_and_coherence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "lexical_resource",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "grammatical_range_and_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "pronunciation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_attempt",
                        to="ielts.examattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TestHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Sarlavha",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "question_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("MCMA", "Multiple Choice (Multiple Answers)"),
                            ("SA", "Short Answer Questions"),
                            ("SC", "Sentence Completion"),
                            ("SUC", "Summary Completion"),
                            ("NC", "Note Completion"),
                            ("FCC", "Flow Chart Completion"),
                            ("TC", "Table Completion"),
                            ("TFNG", "True/False/Not Given"),
                            ("YNNG", "Yes/No/Not Given"),
                            ("MH", "Matching Headings"),
                            ("MI", "Matching Information"),
                            ("MF", "Matching Features"),
                            ("FC", "Form Completion"),
                            ("ML", "Map Labelling"),
                            ("DL", "Diagram Labelling"),
                        ],
                        help_text="The type of question this test head represents.",
                        max_length=10,
                        null=True,
                        verbose_name="Savol turi",
                    ),
                ),
                ("question_data", models.JSONField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tests/pictures/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "listening",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_heads",
                        to="ielts.listeningpart",
                        verbose_name="Listening",
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_heads",
                        to="ielts.readingpassage",
                        verbose_name="Reading",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="test_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="ielts.testhead",
            ),
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(blank=True, max_length=255)),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Whether the answer is correct"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="ielts.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="ielts.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question__order"],
            },
        ),
        migrations.CreateModel(
            name="WritingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual word count of the answer",
                        null=True,
                    ),
                ),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "band_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "task_response_or_achievement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "coherence_and_cohesion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "lexical_resource",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "grammatical_range_and_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "feedback",
                    models.JSONField(
                        blank=True,
                        default=ielts.models.WritingAttempt._default_feedback,
                        help_text="Detailed feedback from AI on the writing task.",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_attempts",
                        to="ielts.examattempt",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ielts.writingtask",
                    ),
                ),
            ],
            options={
                "ordering": ["submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["student"], name="exam_attemp_student_bc66a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam", "status"], name="exam_attemp_exam_id_33f189_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["student"], name="exam_result_student_836d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(fields=["exam"], name="exam_result_exam_id_14ebd6_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["status"], name="scheduled_e_status_d3370c_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["pin_code"], name="scheduled_e_pin_cod_22454a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["start_date", "expire_date"],
                name="scheduled_e_start_d_6c223a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("test_head", "order")},
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["exam_attempt", "is_correct"],
                name="exams_usera_exam_at_b709f0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("exam_attempt", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="writingattempt",
            unique_together={("exam_attempt", "task")},
        ),
        migrations.AddIndex(
            model_name="mockexam",
            index=models.Index(fields=["exam_type"], name="exams_exam_ty_3674fc_idx"),
        ),
    ]
