# Generated by Django 5.2.7 on 2025-11-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhead',
            name='example',
            field=models.JSONField(blank=True, help_text='Example question and answer to show users before the actual questions.', null=True, verbose_name='Example'),
        ),
    ]
