# Generated by Django 5.2.7 on 2025-11-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ielts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="created_by",
        ),
    ]
