# Generated by Django 5.2.7 on 2025-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_add_example_to_testhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningpart',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speakingtopic',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
    ]
