# Generated by Django 5.2.7 on 2025-11-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_remove_exam_created_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useranswer',
            new_name='ielts_usera_exam_at_70cbb0_idx',
            old_name='exams_usera_exam_at_b709f0_idx',
        ),
        migrations.AddField(
            model_name='listeningpart',
            name='is_authentic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='is_authentic',
            field=models.BooleanField(default=False),
        ),
    ]
