# Generated by Django 5.2.7 on 2025-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_add_speaking_answer_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='speakinganswer',
            new_name='speaking_an_speakin_b8569a_idx',
            old_name='speaking_an_speakin_idx',
        ),
    ]
