# Generated by Django 5.2.7 on 2025-11-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_rename_exams_usera_exam_at_b709f0_idx_ielts_usera_exam_at_70cbb0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtopic',
            name='is_authentic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='is_authentic',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
