# Generated by Django 5.2.7 on 2025-12-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_listeningpart_is_practice_readingpassage_is_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtopic',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL to TTS-generated audio for this topic (examiner reading the question)', null=True),
        ),
    ]
