# Generated by Django 5.2.7 on 2025-12-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_add_audio_url_to_speaking_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingDefaultAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('PART_1_INTRO', 'Part 1 Introduction'), ('PART_2_INTRO', 'Part 2 Introduction (Before Cue Card)'), ('PART_2_PREP', 'Part 2 Preparation Time Announcement'), ('PART_2_START', 'Part 2 Start Speaking'), ('PART_3_INTRO', 'Part 3 Introduction'), ('TEST_END', 'Test Ending Message')], max_length=20, unique=True, verbose_name='Audio Type')),
                ('audio_url', models.URLField(help_text='URL to the default audio file')),
                ('description', models.TextField(blank=True, help_text='Description of what this audio says', null=True)),
                ('script', models.TextField(blank=True, help_text='The text/script used to generate this audio', null=True)),
                ('voice', models.CharField(default='en-GB-SoniaNeural', help_text='Voice used for TTS generation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Speaking Default Audio',
                'verbose_name_plural': 'Speaking Default Audios',
                'ordering': ['audio_type'],
            },
        ),
    ]
