# Generated by Django 5.2.7 on 2025-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_speakingtopic_is_authentic_writingtask_is_authentic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningpart',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner (Band 3-4)'), ('INTERMEDIATE', 'Intermediate (Band 5-6)'), ('ADVANCED', 'Advanced (Band 7-8)'), ('EXPERT', 'Expert (Band 8.5-9)')], default='INTERMEDIATE', max_length=20, verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner (Band 3-4)'), ('INTERMEDIATE', 'Intermediate (Band 5-6)'), ('ADVANCED', 'Advanced (Band 7-8)'), ('EXPERT', 'Expert (Band 8.5-9)')], default='INTERMEDIATE', max_length=20, verbose_name='Difficulty Level'),
        ),
    ]
