# Generated by Django 5.2.7 on 2025-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_add_speaking_default_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingtopic',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='speakingtopic',
            name='cue_card',
        ),
        migrations.RemoveField(
            model_name='speakingtopic',
            name='question',
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='cue_card_points',
            field=models.JSONField(blank=True, help_text='JSON array of cue card points (for Part 2 main question only)', null=True),
        ),
    ]
