# Generated by Django 5.2.7 on 2025-11-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_listeningpart_difficulty_readingpassage_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingattempt',
            name='ai_band_score',
            field=models.CharField(blank=True, help_text='Estimated band score from AI', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='writingattempt',
            name='ai_corrected_essay',
            field=models.TextField(blank=True, help_text='Fully corrected version of the essay', null=True),
        ),
        migrations.AddField(
            model_name='writingattempt',
            name='ai_inline',
            field=models.TextField(blank=True, help_text='Essay with inline highlights using <g>, <v>, <s>, <p> tags', null=True),
        ),
        migrations.AddField(
            model_name='writingattempt',
            name='ai_sentences',
            field=models.JSONField(blank=True, help_text='Array of corrected sentences with explanations', null=True),
        ),
        migrations.AddField(
            model_name='writingattempt',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI summary of mistakes and improvements', null=True),
        ),
    ]
