# Generated by Django 5.2.7 on 2025-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0006_remove_speaking_topic_deprecated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtask',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('LINE_GRAPH', 'Line Graph'), ('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('TABLE', 'Table'), ('MAP', 'Map'), ('PROCESS', 'Process Diagram'), ('FLOW_CHART', 'Flow Chart'), ('MIXED', 'Mixed/Multiple Charts'), ('OTHER', 'Other')], db_index=True, help_text='Type of visual for Task 1 (Academic). Leave empty for Task 2.', max_length=20, null=True, verbose_name='Chart Type'),
        ),
    ]
